[package]
name = "ch04_14_array"
version = "0.1.0"
authors = ["D-RyusukeMatsumoto <matsumoto@dedication.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
